version: "3"

volumes:
  node_module_frontend:
  node_module_BFF:

services:
  frontend:
    container_name: frontend
    image: node:16.8
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/var/app/frontend
      - node_module_frontend:/var/app/frontend/node_modules
    working_dir: /var/app/frontend
    command: bash -c "npm i && npm run build && npm run start"

  BFF:
    container_name: BFF
    image: node:16.8
    ports:
      - 8000:8000
    volumes:
      - ./BFF:/var/app/BFF
      - node_module_BFF:/var/app/BFF/node_modules
    working_dir: /var/app/BFF
    command: bash -c "yarn run start"
    env_file: .env
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./data/session:/var/app/data
    working_dir: /var/app
    command: bash -c "redis-server --appendonly yes"
