import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero */}
      <section className="relative flex justify-center items-center h-screen bg-yellow-300">
        <div>
          <h1 className="text-center text-3xl mb-2">
            Welcome to <span className="text-white">OcOsu</span>
          </h1>

          <Link href="/">
            <a className="block w-max bg-white rounded-md px-6 py-2">Login</a>
          </Link>
        </div>
      </section>

      <main className="container mx-auto">
        {/* POST */}
        <section className="py-32 text-center">
          <h2 className="text-3xl mb-4">Share your Oc!</h2>
          <form action="" className="max-w-2xl mx-auto">
            <textarea
              name="body"
              placeholder="Write your Oc detail"
              className="block resize-y w-full h-32 bg-white rounded-2xl shadow-lg px-8 py-4 mb-8"
            ></textarea>
            <input type="file" className="block" />
            <button
              type="submit"
              className="block mx-auto font-semibold bg-yellow-400 text-white px-8 py-2 rounded-xl shadow-lg"
            >
              Share
            </button>
          </form>
        </section>
      </main>
    </div>
  );
};

export default Home;
